# Put protoc and twirp tooling in it's own image
FROM golang:1.17.7-bullseye AS protoc
RUN apt-get update && apt-get install -y unzip
ENV PROTOBUF_VERSION=3.7.1
RUN wget "https://github.com/protocolbuffers/protobuf/releases/download/v$PROTOBUF_VERSION/protoc-$PROTOBUF_VERSION-linux-x86_64.zip" && \
    unzip "protoc-$PROTOBUF_VERSION-linux-x86_64.zip" -d "/protobuf"

RUN GO111MODULE=on go get github.com/twitchtv/twirp/protoc-gen-twirp@v7.1.0 \
    && GO111MODULE=on go get github.com/gogo/protobuf/protoc-gen-gofast@v1.3.1

ENTRYPOINT ["/protobuf/bin/protoc", "-I/protobuf"]

